In [25]:
import pandas as pd

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [26]:
data = pd.read_csv("vitamin_deficiency_disease_dataset_20260123.csv")

In [27]:
data.head()

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,disease_diagnosis,has_multiple_deficiencies
0,79,Male,24.8,Former,NaN,Active,Vegetarian,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
1,77,Female,39.9,Former,Moderate,Light,Omnivore,Low,Low,Low,...,0,0,0,1,0,0,0,0,Rickets_Osteomalacia,0
2,24,Male,26.4,Former,Heavy,Moderate,Omnivore,Low,High,High,...,1,0,0,0,0,0,0,0,Healthy,0
3,69,Male,23.1,Never,Heavy,Moderate,Vegetarian,High,Low,Low,...,0,0,0,0,0,1,1,0,Anemia,0
4,63,Male,29.6,Never,NaN,Moderate,Vegetarian,Moderate,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0

In [28]:
data.tail()

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,disease_diagnosis,has_multiple_deficiencies
3995,25,Female,21.6,Former,Heavy,Active,Pescatarian,Moderate,Middle,High,...,1,0,0,0,0,0,0,0,Healthy,0
3996,50,Male,29.5,Former,Moderate,Sedentary,Vegetarian,Low,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
3997,34,Female,24.8,Never,NaN,Active,Pescatarian,Moderate,Low,Low,...,0,1,0,0,0,1,1,0,Anemia,0
3998,39,Female,26.9,Former,Heavy,Active,Omnivore,High,Low,High,...,1,0,0,0,0,0,0,0,Anemia,0
3999,41,Female,28.0,Current,NaN,Sedentary,Omnivore,High,High,High,...,0,0,0,0,0,0,1,0,Anemia,0

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        4000 non-null   int64
 1   gender                     4000 non-null   object
 2   bmi                        4000 non-null   float64
 3   smoking_status             4000 non-null   object
 4   alcohol_consumption        2722 non-null   object
 5   exercise_level             4000 non-null   object
 6   diet_type                  4000 non-null   object
 7   sun_exposure               4000 non-null   object
 8   income_level               4000 non-null   object
 9   latitude_region            4000 non-null   object
 10  vitamin_a_percent_rda      4000 non-null   float64
 11  vitamin_c_percent_rda      4000 non-null   float64
 12  vitamin_d_percent_rda      4000 non-null   float64
 13  vitamin_e_percent_rda      4000 non-null   float64
 14  vitamin_b12_percent_rda    4000 non-null   float64
 15  folate_percent_rda         4000 non-null   float64
 16  calcium_percent_rda        4000 non-null   float64
 17  iron_percent_rda           4000 non-null   float64
 18  hemoglobin_g_dl            4000 non-null   float64
 19  serum_vitamin_d_ng_ml      4000 non-null   float64
 20  serum_vitamin_b12_pg_ml    4000 non-null   float64
 21  serum_folate_ng_ml         4000 non-null   float64
 22  symptoms_count             4000 non-null   int64
 23  symptoms_list              2672 non-null   object
 24  has_night_blindness        4000 non-null   int64
 25  has_fatigue                4000 non-null   int64
 26  has_bleeding_gums          4000 non-null   int64
 27  has_bone_pain              4000 non-null   int64
 28  has_muscle_weakness        4000 non-null   int64
 29  has_numbness_tingling      4000 non-null   int64
 30  has_memory_problems        4000 non-null   int64
 31  has_pale_skin              4000 non-null   int64
 32  disease_diagnosis          4000 non-null   object
 33  has_multiple_deficiencies  4000 non-null   int64
dtypes: float64(13), int64(11), object(10)
memory usage: 1.0+ MB

In [30]:
data.describe()

,age,bmi,vitamin_a_percent_rda,vitamin_c_percent_rda,vitamin_d_percent_rda,vitamin_e_percent_rda,vitamin_b12_percent_rda,folate_percent_rda,calcium_percent_rda,iron_percent_rda,...,symptoms_count,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,has_multiple_deficiencies
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,...,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,50.766250,26.105325,90.770850,89.199075,72.216388,89.946125,62.743225,90.382275,82.586300,76.211125,...,1.86725,0.102250,0.269250,0.043500,0.300750,0.265750,0.351250,0.303000,0.161750,0.347250
std,19.306237,4.922746,37.083534,37.505809,42.831000,37.444649,37.396636,37.563684,36.359131,33.226984,...,1.79581,0.303015,0.443626,0.204005,0.458641,0.441787,0.477421,0.459613,0.368267,0.476156
min,18.000000,15.000000,10.000000,10.000000,7.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,34.000000,22.800000,62.600000,60.975000,40.730000,61.700000,32.700000,61.800000,55.600000,51.400000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,51.000000,26.200000,85.500000,83.500000,62.270000,84.050000,55.600000,84.800000,77.100000,71.250000,...,2.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,67.000000,29.400000,115.300000,113.000000,93.317500,114.100000,84.500000,115.200000,105.300000,95.900000,...,3.00000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
max,84.000000,45.000000,219.000000,250.000000,275.600000,237.600000,243.600000,226.600000,232.700000,211.400000,...,9.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [31]:
print("Rows and Columns:", data.shape)

Rows and Columns: (4000, 34)

In [32]:
print("Columns:", data.columns)

Columns: Index(['age', 'gender', 'bmi', 'smoking_status', 'alcohol_consumption',
       'exercise_level', 'diet_type', 'sun_exposure', 'income_level',
       'latitude_region', 'vitamin_a_percent_rda', 'vitamin_c_percent_rda',
       'vitamin_d_percent_rda', 'vitamin_e_percent_rda',
       'vitamin_b12_percent_rda', 'folate_percent_rda', 'calcium_percent_rda',
       'iron_percent_rda', 'hemoglobin_g_dl', 'serum_vitamin_d_ng_ml',
       'serum_vitamin_b12_pg_ml', 'serum_folate_ng_ml', 'symptoms_count',
       'symptoms_list', 'has_night_blindness', 'has_fatigue',
       'has_bleeding_gums', 'has_bone_pain', 'has_muscle_weakness',
       'has_numbness_tingling', 'has_memory_problems', 'has_pale_skin',
       'disease_diagnosis', 'has_multiple_deficiencies'],
      dtype='object')

In [33]:
print(data.isnull().sum())

age                             0
gender                          0
bmi                             0
smoking_status                  0
alcohol_consumption          1278
exercise_level                  0
diet_type                       0
sun_exposure                    0
income_level                    0
latitude_region                 0
vitamin_a_percent_rda           0
vitamin_c_percent_rda           0
vitamin_d_percent_rda           0
vitamin_e_percent_rda           0
vitamin_b12_percent_rda         0
folate_percent_rda              0
calcium_percent_rda             0
iron_percent_rda                0
hemoglobin_g_dl                 0
serum_vitamin_d_ng_ml           0
serum_vitamin_b12_pg_ml         0
serum_folate_ng_ml              0
symptoms_count                  0
symptoms_list                1328
has_night_blindness             0
has_fatigue                     0
has_bleeding_gums               0
has_bone_pain                   0
has_muscle_weakness             0
has_numbness_tingling           0
has_memory_problems             0
has_pale_skin                   0
disease_diagnosis               0
has_multiple_deficiencies       0
dtype: int64

In [39]:
X = data.drop("has_fatigue", axis=1)
y = data["has_fatigue"]

In [40]:
print(X.head())
print(y.head())

   age  gender   bmi smoking_status alcohol_consumption exercise_level  \
0   79    Male  24.8         Former                 NaN         Active
1   77  Female  39.9         Former            Moderate          Light
2   24    Male  26.4         Former               Heavy       Moderate
3   69    Male  23.1          Never               Heavy       Moderate
4   63    Male  29.6          Never                 NaN       Moderate

    diet_type sun_exposure income_level latitude_region  ...  \
0  Vegetarian         High         High             Mid  ...
1    Omnivore          Low          Low             Low  ...
2    Omnivore          Low         High            High  ...
3  Vegetarian         High          Low             Low  ...
4  Vegetarian     Moderate         High             Low  ...

                       symptoms_list  has_night_blindness  has_bleeding_gums  \
0                                NaN                    0                  0
1                          bone_pain                    0                  0
2           dry_skin;night_blindness                    1                  0
3  numbness_tingling;memory_problems                    0                  0
4                                NaN                    0                  0

   has_bone_pain  has_muscle_weakness  has_numbness_tingling  \
0              0                    0                      0
1              1                    0                      0
2              0                    0                      0
3              0                    0                      1
4              0                    0                      0

   has_memory_problems  has_pale_skin     disease_diagnosis  \
0                    0              0               Healthy
1                    0              0  Rickets_Osteomalacia
2                    0              0               Healthy
3                    1              0                Anemia
4                    0              0               Healthy

   has_multiple_deficiencies
0                          0
1                          0
2                          0
3                          0
4                          0

[5 rows x 33 columns]
0    0
1    0
2    0
3    0
4    0
Name: has_fatigue, dtype: int64

In [41]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (4000, 33)
Shape of y: (4000,)

In [42]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

Training set size: (3200, 33)
Testing set size: (800, 33)

In [59]:
model = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    activation='tanh',
    solver='adam',
    max_iter=500,
    random_state=42
)

## Task Questions: 
# o	Print number of rows and columns. 
# o	Identify target column. o Check if any missing values exist.

In [50]:
import pandas as pd

# load dataset (change filename if needed)
data = pd.read_csv("vitamin_deficiency_disease_dataset_20260123.csv")

# 1️⃣ Print number of rows and columns
print("Shape of dataset:", data.shape)
print("Rows:", data.shape[0])
print("Columns:", data.shape[1])

# 2️⃣ Identify target column
# 👉 replace 'target' with your actual column name
target_column = 'target'
print("Target column:", target_column)

# 3️⃣ Check missing values
print("\nMissing values in each column:")
print(data.isnull().sum())

# Check if ANY missing value exists
print("\nAny missing value in dataset:", data.isnull().values.any())

Shape of dataset: (4000, 34)
Rows: 4000
Columns: 34
Target column: target

Missing values in each column:
age                             0
gender                          0
bmi                             0
smoking_status                  0
alcohol_consumption          1278
exercise_level                  0
diet_type                       0
sun_exposure                    0
income_level                    0
latitude_region                 0
vitamin_a_percent_rda           0
vitamin_c_percent_rda           0
vitamin_d_percent_rda           0
vitamin_e_percent_rda           0
vitamin_b12_percent_rda         0
folate_percent_rda              0
calcium_percent_rda             0
iron_percent_rda                0
hemoglobin_g_dl                 0
serum_vitamin_d_ng_ml           0
serum_vitamin_b12_pg_ml         0
serum_folate_ng_ml              0
symptoms_count                  0
symptoms_list                1328
has_night_blindness             0
has_fatigue                     0
has_bleeding_gums               0
has_bone_pain                   0
has_muscle_weakness             0
has_numbness_tingling           0
has_memory_problems             0
has_pale_skin                   0
disease_diagnosis               0
has_multiple_deficiencies       0
dtype: int64

Any missing value in dataset: True


# o Display first five examples of x and y. 
# o Print shape of x and y. 
# o What happens when we include target into x? 
# o Explain what axis =1 means?

In [51]:
target = data.columns[-1]

x = data.drop(target, axis=1)
y = data[target]

print("Target column:", target)
print("X shape:", x.shape)
print("y shape:", y.shape)

Target column: has_multiple_deficiencies
X shape: (4000, 33)
y shape: (4000,)

# Change test_size to 0.3. 
# What happens if random_state is removed? 
# Print size of train and test sets.

In [52]:
from sklearn.model_selection import train_test_split

# split data (test_size = 0.3)
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

# print sizes of train and test sets
print("X_train shape:", x_train.shape)
print("X_test shape:", x_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (2800, 33)
X_test shape: (1200, 33)
y_train shape: (2800,)
y_test shape: (1200,)

# Print first 5 rows before and after scaling. 
# What happens if we scale entire dataset before splitting? 
# Why do we use fit_transform() only on training data?

In [61]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# BEFORE scaling
print("First 5 rows of X_train BEFORE scaling:")
print(x_train.head())

# AFTER scaling
print("\nFirst 5 rows of X_train AFTER scaling:")

First 5 rows of X_train BEFORE scaling:
      age  gender   bmi smoking_status alcohol_consumption exercise_level  \
3215   77  Female  28.2         Former                 NaN          Light
3126   43    Male  17.8         Former            Moderate      Sedentary
697    35  Female  15.0        Current            Moderate         Active
3613   20    Male  30.1         Former                 NaN       Moderate
2374   61    Male  25.4         Former               Heavy         Active

        diet_type sun_exposure income_level latitude_region  ...  \
3215  Pescatarian     Moderate         High             Low  ...
3126     Omnivore     Moderate       Middle             Low  ...
697   Pescatarian     Moderate         High             Low  ...
3613   Vegetarian          Low         High             Mid  ...
2374  Pescatarian         High       Middle            High  ...

                 symptoms_list  has_night_blindness  has_fatigue  \
3215                       NaN                    0            0
3126  dry_skin;night_blindness                    1            0
697                        NaN                    0            0
3613           muscle_weakness                    0            0
2374                       NaN                    0            0

      has_bleeding_gums  has_bone_pain  has_muscle_weakness  \
3215                  0              0                    0
3126                  0              0                    0
697                   0              0                    0
3613                  0              0                    1
2374                  0              0                    0

      has_numbness_tingling  has_memory_problems  has_pale_skin  \
3215                      0                    0              0
3126                      0                    0              0
697                       0                    0              0
3613                      0                    0              0
2374                      0                    0              0

         disease_diagnosis
3215               Healthy
3126       Night_Blindness
697                Healthy
3613  Rickets_Osteomalacia
2374               Healthy

[5 rows x 33 columns]

First 5 rows of X_train AFTER scaling: